### ISSUE TITLE
Remove hard-coded requirement for HTTPS delivery

### ISSUE THREAD

**Issue by jaywink** [jaywink/federation#106]
Default to HTTPS protocol. Allow passing in a fallback to HTTP flag (default false) and then fallback to HTTP if given.

See jaywink/socialhome#391

**Comment by jaywink** [comment]
@autogestion so do you think (in your usage) there is anything needed to be done for this still? The fetch and send methods are fine with http I guess now, but I'm not sure about the high level functions.. I can keep this open and check later.

**Comment by autogestion** [comment]
I think it could be closed. It could be reopened if there will be problems with high level functions
