### ISSUE TITLE
Possible signature validation problem with public posts from GangGo

### ISSUE THREAD

**Issue by jaywink** [jaywink/federation#115]
Testing reveals:
* public posts fail to validate the signature
* public comments succeed with validate
* private posts succeed with validate

Check ordering of elements within XML and whether something interesting comes out of there.

@Zauberstuhl

**Comment by Zauberstuhl** [comment]
> Some platforms ..

thanks for anonymity :D

**Comment by jaywink** [comment]
Well it could be other (old or future) platforms too! Great we found this out, was going crazy... long live aggressive debug logging :+1:
